# Generated by Django 3.2.9 on 2022-01-18 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PenpalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronoun', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('hobby1', models.CharField(default='First Hobby', max_length=50)),
                ('hobby2', models.CharField(blank=True, default='Second Hobby', max_length=50)),
                ('hobby3', models.CharField(blank=True, default='Third Hobby', max_length=50)),
                ('childAge1', models.IntegerField(default=0)),
                ('childAge2', models.IntegerField(blank=True, default=0)),
                ('childAge3', models.IntegerField(blank=True, default=0)),
                ('childAge4', models.IntegerField(blank=True, default=0)),
                ('childAge5', models.IntegerField(blank=True, default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
