# Generated by Django 3.2.9 on 2022-01-25 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PenpalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language1', models.CharField(choices=[('English', 'Eng'), ('Spanish', 'Spa'), ('French', 'Fra'), ('German', 'Deu'), ('Portuguese', 'Por')], default='English', max_length=10)),
                ('language2', models.CharField(blank=True, choices=[('English', 'Eng'), ('Spanish', 'Spa'), ('French', 'Fra'), ('German', 'Deu'), ('Portuguese', 'Por')], default='English', max_length=10, null=True)),
                ('language3', models.CharField(blank=True, choices=[('English', 'Eng'), ('Spanish', 'Spa'), ('French', 'Fra'), ('German', 'Deu'), ('Portuguese', 'Por')], default='English', max_length=10, null=True)),
                ('name', models.CharField(default='Your name', max_length=50)),
                ('pronoun', models.CharField(default='Your preferred pronoun/s)', max_length=50)),
                ('age', models.IntegerField(default='Your age')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('hobby1', models.CharField(default='A hobby', max_length=50)),
                ('hobby2', models.CharField(blank=True, default='Second hobby (optional)', max_length=50, null=True)),
                ('hobby3', models.CharField(blank=True, default='Third hobby (optional)', max_length=50, null=True)),
                ('childAge1', models.IntegerField(default="Your child's age")),
                ('childAge2', models.IntegerField(blank=True, default="Second child's age (optional)", null=True)),
                ('childAge3', models.IntegerField(blank=True, default="Third child's age (optional)", null=True)),
                ('childAge4', models.IntegerField(blank=True, default="Fourth child's age (optional)", null=True)),
                ('childAge5', models.IntegerField(blank=True, default="Fifth child's age (optional)", null=True)),
                ('email', models.EmailField(default='Your email address', max_length=50)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
