# Generated by Django 3.2.9 on 2022-01-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penpals', '0002_auto_20220122_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penpalprofile',
            name='age',
            field=models.IntegerField(default='Your age'),
        ),
        migrations.AlterField(
            model_name='penpalprofile',
            name='childAge1',
            field=models.IntegerField(default="Your child's age"),
        ),
        migrations.AlterField(
            model_name='penpalprofile',
            name='childAge2',
            field=models.IntegerField(blank=True, default="Second child's age (optional)", null=True),
        ),
        migrations.AlterField(
            model_name='penpalprofile',
            name='childAge3',
            field=models.IntegerField(blank=True, default="Third child's age (optional)", null=True),
        ),
        migrations.AlterField(
            model_name='penpalprofile',
            name='childAge4',
            field=models.IntegerField(blank=True, default="Fourth child's age (optional)", null=True),
        ),
        migrations.AlterField(
            model_name='penpalprofile',
            name='childAge5',
            field=models.IntegerField(blank=True, default="Fifth child's age (optional)", null=True),
        ),
        migrations.AlterField(
            model_name='penpalprofile',
            name='email',
            field=models.EmailField(default='Your email address', max_length=50),
        ),
        migrations.AlterField(
            model_name='penpalprofile',
            name='hobby1',
            field=models.CharField(default='A hobby', max_length=50),
        ),
        migrations.AlterField(
            model_name='penpalprofile',
            name='hobby2',
            field=models.CharField(blank=True, default='Second hobby (optional)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='penpalprofile',
            name='hobby3',
            field=models.CharField(blank=True, default='Third hobby (optional)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='penpalprofile',
            name='name',
            field=models.CharField(default='Your name', max_length=50),
        ),
        migrations.AlterField(
            model_name='penpalprofile',
            name='pronoun',
            field=models.CharField(default='Your preferred pronoun/s)', max_length=50),
        ),
    ]
