# Generated by Django 3.2.9 on 2022-01-24 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('penpals', '0003_auto_20220122_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='penpalprofile',
            name='user',
            field=models.OneToOneField(default='Your username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
