# Generated by Django 3.2.9 on 2022-01-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penpals', '0005_auto_20220127_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penpalprofile',
            name='language1',
            field=models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('French', 'French'), ('German', 'German'), ('Portuguese', 'Portuguese')], default='English', max_length=10),
        ),
        migrations.AlterField(
            model_name='penpalprofile',
            name='language2',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Spanish', 'Spanish'), ('French', 'French'), ('German', 'German'), ('Portuguese', 'Portuguese')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='penpalprofile',
            name='language3',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Spanish', 'Spanish'), ('French', 'French'), ('German', 'German'), ('Portuguese', 'Portuguese')], max_length=10, null=True),
        ),
    ]
