# Generated by Django 3.2.9 on 2022-01-17 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WriterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language1', models.CharField(choices=[('ENG', 'English'), ('SPA', 'Spanish'), ('FRA', 'French'), ('DEU', 'German'), ('POR', 'Portuguese')], default='ENG', max_length=3)),
                ('language2', models.CharField(blank=True, choices=[('ENG', 'English'), ('SPA', 'Spanish'), ('FRA', 'French'), ('DEU', 'German'), ('POR', 'Portuguese')], default='ENG', max_length=3)),
                ('language3', models.CharField(blank=True, choices=[('ENG', 'English'), ('SPA', 'Spanish'), ('FRA', 'French'), ('DEU', 'German'), ('POR', 'Portuguese')], default='ENG', max_length=3)),
                ('pronoun', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('hobby1', models.CharField(default='First Hobby', max_length=50)),
                ('hobby2', models.CharField(blank=True, default='Second Hobby', max_length=50)),
                ('hobby3', models.CharField(blank=True, default='Third Hobby', max_length=50)),
                ('childAge1', models.IntegerField(default=0)),
                ('childAge2', models.IntegerField(blank=True, default=0)),
                ('childAge3', models.IntegerField(blank=True, default=0)),
                ('childAge4', models.IntegerField(blank=True, default=0)),
                ('childAge5', models.IntegerField(blank=True, default=0)),
                ('default_email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='default_email', to=settings.AUTH_USER_MODEL)),
                ('default_first_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='default_first_name', to=settings.AUTH_USER_MODEL)),
                ('default_last_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='default_last_name', to=settings.AUTH_USER_MODEL)),
                ('default_username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='default_username', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
