# Generated by Django 3.2.9 on 2022-01-10 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Profile',
        ),
    ]
