# Generated by Django 3.2.9 on 2022-01-10 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_item_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Item',
        ),
    ]
