# Generated by Django 3.2.9 on 2022-01-14 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220112_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='childAge1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='childAge2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='childAge3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='childAge4',
        ),
        migrations.RemoveField(
            model_name='item',
            name='childAge5',
        ),
        migrations.RemoveField(
            model_name='item',
            name='email',
        ),
        migrations.RemoveField(
            model_name='item',
            name='hobby1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='hobby2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='hobby3',
        ),
    ]
