# Generated by Django 3.2.9 on 2022-01-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220114_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='childAge1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='childAge2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='childAge3',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='childAge4',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='childAge5',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='email',
            field=models.EmailField(default='myemail@email.com', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='hobby1',
            field=models.CharField(default='First Hobby', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='hobby2',
            field=models.CharField(blank=True, default='Second Hobby', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='hobby3',
            field=models.CharField(blank=True, default='Third Hobby', max_length=50, null=True),
        ),
    ]
