# Generated by Django 3.2.9 on 2022-01-17 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20220114_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='childAge1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='childAge2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='childAge3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='childAge4',
        ),
        migrations.RemoveField(
            model_name='item',
            name='childAge5',
        ),
        migrations.RemoveField(
            model_name='item',
            name='email',
        ),
        migrations.RemoveField(
            model_name='item',
            name='hobby1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='hobby2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='hobby3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='language1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='language2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='language3',
        ),
    ]
