# Generated by Django 3.2.9 on 2022-01-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_item_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
