# Generated by Django 3.2.9 on 2022-01-21 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stationery',
            options={'verbose_name_plural': 'Stationery'},
        ),
    ]
